### ISSUE TITLE
Dapp-Manager exposes a SQL-dump when reading data

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/dapp-manager#100]
Hello. 

I just noticed that in one of our backend's response some SQL data dump was exposed by the Dapp-Manager

This is our functions that's used on the portal.
```ts
export default function CliAdapter(dManagerCmd: ICmdRunner, dStatsCmd: ICmdRunner): ICliAdapter {
  async function getDetails(command: string, appId: string, ensureAlive = true) {
    const result = await dManagerCmd.run("read", appId, command, ensureAlive ? "" : "--no-ensure-alive");
    return result.stdout.trim();
  }
```

Here's some of the data that was in the response

![image](https://user-images.githubusercontent.com/33448819/230339556-9ad14aca-5ac5-4c18-a7e4-e677858cf8c1.png)

**Comment by shadeofblue** [comment]
this is not an issue with the `dapp-manager` or `dapp-runner` ... it's the app's responsibility not to expose any vulnerable data in its stdout/stderr strings
