### ISSUE TITLE
Pid recycling and `app_id`

### ISSUE THREAD

**Issue by johny-b** [golemfactory/dapp-manager#12]
(Note: it is assumed #18 is already merged)

```
dapp = DappManager.start(...)
sleep(10000)
dapp.kill()
```

In the current implementation, we don't know if this:
A) stopped app `my_app_id` we started before
B) stopped some other app, because:
* app `my_app_id` was no longer running (e.g. because the process exited)
* pid was recycled, and some other `unlucky_app_id` got the same pid

Solution seems to be pretty easy - "just ensure in the database that different apps can't have the same `pid`".

Hopefully, this will quite be easy:
1. App starts
2. We have the new pid
3. We check if there is any known app with the same pid
4. If yes, save the information that the old app already finished (more on this in #11)

**IMPORTANT CAVEAT***

As the "database" is per-user, we could still have this sort of a problem with multiple users on the same system.
But:
* this **might** be totally harmless - the check "is this dapp running? (-> #13) " could (maybe?) check if this is our process. If not, dapp is not running
* also, we can't interfere with the process started by other user, so this will not be very harmfull

**Comment by shadeofblue** [comment]
we can also check whether the process was started before the pidfile was created -> #56
