### ISSUE TITLE
access the `yapapi` `log` file from the command line

### ISSUE THREAD

**Issue by johny-b** [golemfactory/dapp-manager#33]
This will be similar to `raw-state` and `raw-data`.
No changes in the `dapp-runner` are required.

Note about names:
* `raw-data` should **probably** be renamed to `raw-logs` or so, so that we have `yagna_dapp_manager logs` that is more-or-less the same as `docker logs` - i.e. contains data from the containers.
* we'll probably have things like `runner-logs` for STDOUT/STDERR from the runner
* --> meaningful name? Maybe just explicit `yapapi-logs` would be best?

UPDATE: let's keep command names without changes for now and rethink them in the future.

**Comment by shadeofblue** [comment]
closing via: https://github.com/golemfactory/dapp-manager/pull/36/files
