### ISSUE TITLE
dapp-manager read not usable with tail -n 1 SCT

### ISSUE THREAD

**Issue by grisha87** [golemfactory/dapp-manager#79]
## Steps to reproduce

1. Start an application
2. Read its state with `app-manager read state b47bf9b08e064f40b5ddef83e670ee30 --no-ensure-alive | tail -n 1`

## Expected result

I should get the latest line of the state, properly populated one.

## Actual result

The way `dapp-manager read` works results with an empty line being the output of the command. If I want to get the last populated line I need to go with `tail -n 2` which really shouldn't be the case :)

**Comment by grisha87** [comment]
Possibly linked to #92

**Comment by shadeofblue** [comment]
could you verify that it's fixed in the current master version of `dapp-manager`? @grisha87

**Comment by shadeofblue** [comment]
closing via https://github.com/golemfactory/dapp-manager/pull/99
