### ISSUE TITLE
As SCT team, we want dapp-manager to warn before/prevent running apps with expired manifest signatures

### ISSUE THREAD

**Issue by grisha87** [golemfactory/dapp-manager#80]
## Why?

In our current development scenario it's occasionally the case, that the dapp's networking manifest signature becomes obsolete due to signing certificate expiration. This leads to the provider rejecting the payload and the particular payload remains as `pending` all the time, rendering the application unusable.

## What needs to be changed?

We would like dapp-manager to take the responsibility and support the user (in this case SCT team, but in an local scenario, a developer trying to use `dapp-manager` from running into that issue and providing proper warning/error message when running `dapp-manager start`.

Ideally, we would like to go with a "fail fast" approach, where calling `dapp-manager start` with a problematic descriptor file would immediately result with an error explaining the situation and exiting with a non-zero code.

Problematic descriptor means:
* file which contains a certificate which has a high chance of getting rejected due to certificate expiry
* or there's a miss-match between the signature, certificate and manifest which also can cause rejection

This behavior could be overridden (SCT team doesn't really need that) by a switch like `--ignore-cert-issues` if someone would really run an app which is surely not going to be operational.

## Acceptance Criteria

* Given a descriptor file contains a certificate which is not within validity period, when I try to start a dapp with that descriptor, then dapp-manager actively blocks it by printing a proper error with description and exiting with a non-zero code.

**Comment by shadeofblue** [comment]
closed via https://github.com/golemfactory/dapp-runner/pull/112
