### ISSUE TITLE
As a developer, I want dapp-manager to support a "prune" command

### ISSUE THREAD

**Issue by grisha87** [golemfactory/dapp-manager#93]
## Why?

... so that we can cleanup resources of applications which are `dead` (residing log files and other artefacts of the execution).

## What needs to be changed?

We would like to request a `dapp-manager prune` command which after confirmation will remove/clean-up data left after executing the apps (inspired by `docker [type] prune`.

## Acceptance Criteria

* The command is supported by dapp-manager and frees my disk space from all data of apps which are "dead"

**Comment by shadeofblue** [comment]
@grisha87 `dapp-manager` already supports `prune`... 

I mean: 

```
$ dapp-manager
Usage: dapp-manager [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
[...]
  prune         Remove data for non-running apps.
```

is is there anything else that you need here?
